<table id="sortable_table" class="datagrid">
    <thead>
        <th>Language</th>
        <th>Active</th>
    </thead>
    <tfoot class="invisible">
        <tr>
            <td colspan="0"></td>
        </tr>
    </tfoot>
    <tbody>
        <?php foreach ($this->results as $row): ?>
            <tr>
                <td><?= $row->language ?></td>  
                <td><?= ($row->active) ? "Y" : "N" ?></td>   
            </tr>                               
        <?php endforeach ?>                     
    </tbody>
</table>