<center>
    <img src="<?= $this->dir_images . "/tup.jpg" ?>" width="150" height="150" alt="SUCCESS" />
    <br />
    <font face="verdana" color="009900" size =-1>
        <strong><?= $this->message ?></strong>
    </font>
    <br /><br /><br /><br />
    <a href="javascript:history.go(-1)">Go Back</a> &nbsp;|&nbsp; 
    <a href="javascript:window.opener.location.reload(true); window.close();">Close Window</a>
</center>