
<?php if ($this->success): ?>
    <center>
        <img src="<?= $this->dir_images . "/tup.jpg" ?>" width="150" height="150" alt="SUCCESS" />
        <br />
        <font face="verdana" color="009900" size =-1>
            <strong><?= $this->success ?></strong>
        </font>
        <br /><br /><br /><br />
        <a href="javascript:window.opener.location.reload(true); window.close();">Close Window</a>
    </center>
<?php else: ?>
    <?php
        if (!(empty($this->errors)))
            echo $this->partial('_formErrorMsg.phtml', array('errors' => $this->errors));
        if (!(empty($this->warnings)))
            echo $this->partial('_formWarnMsg.phtml', array('warnings' => $this->warnings));
    ?>

<form action="<?= $this->url(array("controller" => "baby-study", "action" => "{$this->type}-confirm")) ?>" method="post" accept-charset="utf-8">
    <input type="hidden" name="studyhistory[id]" value="<?= $this->study_history_id ?>" id="id" />
    
<table cellspacing="0" cellpadding="5" class="form">
    <tr>
        <td class="label">
            Serial No
        </td>
        <td>
            <label></label>
            <?= $this->baby_id ?>
            <input type="hidden" name="studyhistory[baby_id]" value="<?= $this->baby_id ?>" id="baby_id">
        </td>
    </tr>   
    <tr>
        <td class="label">
            Research Details
        </td>
        <td>
            <label>Lab: </label>
            <?= $this->lab ?>
            <label>Study: </label>
            <?= $this->formSelect('studyhistory[study_id]', ($this->studyhistory['study_id']) ? $this->studyhistory['study_id'] : $this->study_id, null, $this->studyOptions) ?>
        </td>
    </tr>
    <tr>
        <td class="label">Appointment</td>
        <td>
            <label>Date</label>&nbsp;&nbsp;&nbsp;
            <?= $this->formSelectDate(
                array(
                    'studyhistory[appointment][year]',
                    'studyhistory[appointment][month]',
                    'studyhistory[appointment][day]'
                ),
                $this->date,
                null,
                array(
                    'year_start'=>date('Y')-1,
                    'year_end'=>date('Y')+2
                )
            ) ?>
            <em>(MM/DD/YY)</em>
            <p class="br"></p>
            <label>Time</label>&nbsp;&nbsp;
            <?= $this->formSelectTime("studyhistory[appointment]", $this->time, null, array("addBy" => 5)) ?>
            <em>(HH:MM)</em>
        </td>
    </tr>
    <tr>
        <td class="label">
            Comments
        </td>
        <td>
            <label></label>
            <textarea name="studyhistory[comments]" id="comments" rows="4" cols="42"><?= $this->studyhistory["comments"] ?></textarea>
        </td>
    </tr>
</table>
<p>
    <input type="submit" name="save" value="Save Changes">
    &nbsp;
    <input type="submit" name="confirm" value="Save and Confirm Appointment">
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <input type="submit" name="confirm" value="Cancel Appointment">
</p>
</form>
<?php endif ?>