<h2 class=our_list> Confirm Appointments </h2>

<?php
    if (!(empty($this->errors)))
        echo $this->partial('_formErrorMsg.phtml', array('errors' => $this->errors));
    if (!(empty($this->warnings)))
        echo $this->partial('_formWarnMsg.phtml', array('warnings' => $this->warnings));
?>
<??>
<form action="<?= $this->url(array("controller" => "appointment", "action" => "confirm"), null, true) ?>" method="post" accept-charset="utf-8">
    <table cellspacing="0" cellpadding="5" class="form">
        <tr>
            <td class="label">Researcher Scheduled</td>
            <td width="70%"><?= $this->formSelect("confirm[researcher]", $this->confirm["researcher"], null, $this->researcherOptions) ?></td>
        </tr>
        <tr>
            <td class="label">Study Scheduled</td>
            <td width="70%"><?= $this->formSelect("confirm[study]", $this->confirm["study"], null, $this->studyOptions) ?></td>
        </tr>
        <tr>
            <td class="label">Date of Study</td>
            <td width="70%">
                &nbsp;From&nbsp;&nbsp;
                <?= $this->formSelectDate(
                    array(
                        'confirm[date1][year]',
                        'confirm[date1][month]',
                        'confirm[date1][day]'
                    ),
                    ($this->confirm["date1"]) ? $this->confirm["date1"] : date("Y-m-d"),
                    null,
                    array(
                        'year_start'=>date('Y')-1,
                        'year_end'=>date('Y')+2
                    )
                ) ?>
                <p class="br"></p>
                &nbsp;To&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <?= $this->formSelectDate(
                    array(
                        'confirm[date2][year]',
                        'confirm[date2][month]',
                        'confirm[date2][day]'
                    ),
                    ($this->confirm["date2"]) ? $this->confirm["date2"] : date("Y-m-d", strtotime("+1 day")),
                    null,
                    array(
                        'year_start'=>date('Y')-1,
                        'year_end'=>date('Y')+2
                    )
                ) ?>
            </td>
        </tr>
        <tr>
            <td class="label">Select all dates</td>
            <td width="70%">
                <input type="checkbox" name="confirm[alldates]" value="1" <?= ($this->confirm["alldates"]) ? "checked='checked'" : "" ?>>
            </td>
        </tr>
        <tr>
            <td class="label">Records per page :</td>
            <td width="70%"><?= $this->formSelect("confirm[per_page]", ($this->confirm["per_page"]) ? $this->confirm["per_page"] : 10, null, $this->perPageOptions) ?>
                &nbsp;               
            </td>
        </tr>
    </table>
    <br />
    <input type="submit" value="Get Records &rarr;">&nbsp;&nbsp;&nbsp;<input type="reset" value="Reset" id="reset">
    
</form>