<h2 class=our_list> Appointment Outcome </h2>

<?php
    if (!(empty($this->errors)))
        echo $this->partial('_formErrorMsg.phtml', array('errors' => $this->errors));
    if (!(empty($this->warnings)))
        echo $this->partial('_formWarnMsg.phtml', array('warnings' => $this->warnings));
?>
<??>
<form action="<?= $this->url(array('controller' => "appointment", 'action' => 'outcome'), null, true) ?>" method="post" accept-charset="utf-8">
    <table cellspacing="0" cellpadding="5" class="form">
        <tr>
            <td class="label">Researcher Scheduled</td>
            <td width="70%"><?= $this->formSelect("outcome[researcher]", $this->outcome["researcher"], null, $this->researcherOptions) ?></td>
        </tr>
        <tr>
            <td class="label">Study Scheduled</td>
            <td width="70%"><?= $this->formSelect("outcome[study]", $this->outcome["study"], null, $this->studyOptions) ?></td>
        </tr>
        <tr>
            <td class="label">Date of Study</td>
            <td width="70%">
                &nbsp;From&nbsp;&nbsp;
                <?= $this->formSelectDate(
                    array(
                        'outcome[date1][year]',
                        'outcome[date1][month]',
                        'outcome[date1][day]'
                    ),
                    ($this->outcome["date1"]) ? $this->outcome["date1"] : date("Y-m-d", strtotime("+1 day")),
                    null,
                    array(
                        'year_start'=>date('Y')-1,
                        'year_end'=>date('Y')+2
                    )
                ) ?>
                <p class="br"></p>
                &nbsp;To&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <?= $this->formSelectDate(
                    array(
                        'outcome[date2][year]',
                        'outcome[date2][month]',
                        'outcome[date2][day]'
                    ),
                    ($this->outcome["date2"]) ? $this->outcome["date2"] : date("Y-m-d", strtotime("+2 day")),
                    null,
                    array(
                        'year_start'=>date('Y')-1,
                        'year_end'=>date('Y')+2
                    )
                ) ?>
            </td>
        </tr>
        <tr>
            <td class="label">Select all dates</td>
            <td width="70%">
                <input type="checkbox" name="outcome[alldates]" value="1" <?= ($this->outcome["alldates"]) ? "checked='checked'" : "" ?>>
            </td>
        </tr>
        <tr>
            <td class="label">Records per page :</td>
            <td width="70%"><?= $this->formSelect("outcome[per_page]", ($this->outcome["per_page"]) ? $this->outcome["per_page"] : 10, null, $this->perPageOptions) ?>
                &nbsp;               
            </td>
        </tr>
    </table>
    <br />
    <input type="submit" value="Get Records &rarr;">&nbsp;&nbsp;&nbsp;<input type="reset" value="Reset" id="reset">
    
</form>