<div align="right">
    <a href="<?= $this->url(array("action" => "list", "view_archive" => 2)) ?>" <?= ($this->viewActive) ? "style='font-style:italic'" : "" ?>>
        View Only Active</a> | 
    <a href="<?= $this->url(array("action" => "list", "view_archive" => 1)) ?>" <?= ($this->viewArchived) ? "style='font-style:italic'" : "" ?>>
        View Only Archived</a> | 
    <a href="<?= $this->url(array("action" => "list", "view_archive" => 0)) ?>" <?= ($this->viewAll) ? "style='font-style:italic'" : "" ?>>
        View All</a> |
    <a href="javascript:window.close();">Close Window</a></div>
<br />

<table id="sortable_table" class="datagrid">
    <caption>Studies</caption>
    <thead>
        <th mochi:format="istr" scope="col">Id</th>
        <th mochi:format="isoDate" scope="col">Date Entered</th>
        <th mochi:format="istr" scope="col">Study</th>
        <th mochi:format="istr" scope="col">Researcher</th>
        <th mochi:format="istr" scope="col">Lab</th>
        <th mochi:format="isoDate" scope="col">Lower Age</th>
        <th mochi:format="isoDate" scope="col">Upper Age</th>
        <th mochi:format="istr" scope="col">GCal Calendar ID</th>
        <th mochi:format="istr" scope="col">Active</th>
    </thead>
    <tfoot>
        <tr>
            <td colspan="10" align="center"><a href="javascript:window.close();">Close Window</a></td>
        </tr>
    </tfoot>
    <tbody>
        <?php foreach ($this->results as $rowNum => $row): ?>
            <tr>
                <td><?= str_pad($row['id'], $this->idPad, 0, STR_PAD_LEFT) ?></td>
                <td><?= $row['date_of_entry'] ?></td>
                <td><?= $row['study'] ?></td>      
                <td><?= $row['researcher'] ?></td>
                <td><?= $row['lab'] ?></td>
                <td><?= $row['lower_age'] ?></td>
                <td><?= $row['upper_age'] ?></td>
                <td><?= $row['gcal_calendar_id'] ?></td>
                <td><?= ($row['to_use']) ? "Y" : "N" ?></td>
            </tr>                               
        <?php endforeach ?>                     
    </tbody>
</table>
