<div align="center">
    <?php 
    switch ($this->displayPartial):
        case 'new':
        case 'update':
            echo $this->partial('/contacthistory/_form.phtml', $this);
            break;
        case 'success':
            echo $this->partial('/contacthistory/success.phtml', $this);
            break;
        case 'default':
        case 'view':
            echo $this->partial('/contacthistory/view.phtml', $this);
            break;
    endswitch;
    ?>
    <hr />
    
    <iframe src ='<?= $this->url(array("controller" => "contacthistory", "action" => "list")); ?>' width="100%" height="100%" frameborder="0">
      <p>Your browser does not support iframes.</p>
    </iframe>
</div>