<?php
    if (!(empty($this->errors)))
        echo $this->partial('_formErrorMsg.phtml', array('errors' => $this->errors));
    if (!(empty($this->warnings)))
        echo $this->partial('_formWarnMsg.phtml', array('warnings' => $this->warnings));
?>
<form action="" method="post" accept-charset="utf-8">
    Attempt#: <?= $this->formText('attempt', $this->attempt, array('size' => 3, 'maxlength' => 3)) ?><br />
    Date: <?= $this->formSelectMonth('date[month]', $this->date[1]) ?>
    <?= $this->formSelectDay('date[day]', $this->date[2]) ?>
    <?= $this->formSelectYear('date[year]', $this->date[0], null, array('year_start'=>date('Y')-10, 'year_end'=>date('Y')+1)) ?>&nbsp;&nbsp;&nbsp;
    Time: <?= $this->formSelectHour('time[hour]', $this->time[0]) ?> : 
    <?= $this->formSelectMinute('time[minute]', $this->time[1]) ?><br/>
    <hr>
    
    <fieldset>
        <legend>ID: <?= $this->baby_id ?></legend>
        <ol>
            <li>
                <label for="attempt">Attempt </label>
                <?= $this->formText('attempt', $this->attempt, array('size' => 3, 'maxlength' => 3)) ?>
            </li>
            <li>
                <fieldset>
                    <legend>Date/Time</legend>
                    <div>
                        <div>
                            <?= $this->formSelectMonth('date[month]', $this->date[1]) ?>
                            <?= $this->formSelectDay('date[day]', $this->date[2]) ?>
                            <?= $this->formSelectYear('date[year]', $this->date[0], null, array('year_start'=>date('Y')-10, 'year_end'=>date('Y')+1)) ?>
                        </div>
                        <div> 
                            <?= $this->formSelectHour('time[hour]', $this->time[0]) ?> : 
                            <?= $this->formSelectMinute('time[minute]', $this->time[1]) ?>
                        </div>
                    </div>
                </fieldset>
            </li>
            <li>
                <hr>
            </li>
            <li>
                <label>Caller:</label><?= $this->caller ?>
            </li>
            <li>
                <fieldset>
                    <legend>Contact Details</legend>
                    <div>
                        <div>
                            <?= $this->formSelect('contact_type_id', $this->contact_type_id, null, $this->contact_types) ?>
                            <label for="contact_type_id">Type of Contact </label>
                        </div>
                        <div>
                            <?= $this->formSelect('contact_method', $this->contact_method, null, $this->contact_methods) ?>
                            <label for="contact_method_id">Method of Contact </label>
                        </div>
                        <div>                            
                            <?= $this->formSelect('contact_outcome_id', $this->contact_outcome_id, null, $this->contact_outcomes) ?>
                            <label for="contact_outcome_id">Contact Outcome </label>
                        </div>
                    </div>
                </fieldset>
            </li>
            <li>
                <label for="contact_callback">Callback</label>
                <?= $this->formSelect('contact_callback', $this->contact_callback, null, $this->contact_callbacks) ?>
                <span class="note">When should MIRG call back?</span>
            </li>
            <li>
                <hr>
            </li>
            <li>
                <fieldset>
                    <legend>About</legend>
                    <div>
                        <div>
                            <label for="study_id">Study</label><?= $this->formSelect('study_id', $this->study_id, null, $this->studies) ?>
                        </div>
                        <div>
                            <label for="researcher_id">Researcher</label><?= $this->formSelect('researcher_id', $this->researcher_id, null, $this->researchers) ?>
                        </div>
                    </div>
                </fieldset>
            </li>
            <li>
                <hr>
            </li>
            <li>
                <label for="comment">Comment</label>
                <?= $this->formTextArea('comment', $this->comment) ?>
            </li>
        </ol>
    </fieldset>    
</form>
