<html>

<head>
    <meta http-equiv="content-type" content="text/html; charset=ISO-8859-1">
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/dojo/1.5/dojo/dojo.xd.js"
        djConfig="parseOnLoad: true"></script>
    <?= $this->headLink() ?>
        
    <?= $this->headStyle() ?>
    
    <?= $this->headScript() ?>
    
    <?= $this->headTitle("Yale Baby Database") ?>
    
    
</head>
<body bgcolor="#FFFFFF" class="claro">
<img src="<?= "{$this->dir_images}/ajax-loader.gif" ?>" id="busy" style="display:none">
    <? $header = ($this->headerFile) ? $this->headerFile : 'header.phtml' ?>
    <?= $this->partial($header) ?>
    <?= $this->layout()->content ?>
    <?= $this->partial('footer.phtml') ?>
</body>
</html>