<html>

<head>
<?php
	header("Pragma: public");
	header("Cache-Control: no-store, no-cache, must-revalidate");
	header("Cache-Control: pre-check=0, post-check=0, max-age=0");
	header("Pragma: no-cache");
	header("Expires: 0");
	header("Content-Transfer-Encoding: none");
	header("Content-Type: application/vnd.ms-excel;");
	header("Content-type: application/x-msexcel");
	header("Content-Disposition: attachment; filename=baby-search-results_".date('Ymd').".xls");
?>
</head>
<body bgcolor="#FFFFFF">
    <?= $this->layout()->content ?>
</body>
</html>
