<div id="wrapper">

	<div id="content">
	
		<div class="post">
		
			<h2><a href="#">Lorem Ipsum Dolor Sit Amet</a></h2>
			
      <?php $form = $this->dbForm($this->manual) ?>
      <?= $form->begin() ?>
      <table class="contacts" cellspacing="0" summary="Contacts template">
      <tr>
        <td class="contactDept" colspan="3">Manual Entry</td>
      </tr>
      <tr>
        <td>Mother</td>
      </tr>
      <tr>
        <td class="contact" width="50%">First Name: <?= $form->motherfirst ?></td>
        <td class="contact" width="50%">Last Name: <?= $form->motherlast ?></td>
      </tr>
      <tr>
        <td>Father</td>
      </tr>
      <tr>
        <td class="contact" width="50%">First Name: <?= $form->fatherfirst ?></td>
        <td class="contact" width="50%">Last Name: <?= $form->fatherlast ?></td>
      </tr>
      <tr>
        <td class="contact" width="50%">First Name: <?= $form->fatherfirst ?></td>
        <td class="contact" width="50%">Last Name: <?= $form->fatherlast ?></td>
      </tr>
      <tr>
        <td class="contact" width="50%"><?= $this->formSubmit('Submit') ?></td>
        <td class="contact" width="50%">Reset</td>
      </tr>
      </table>
      <?= $form->end() ?>
			
			<p>According to <cite title="Wikipedia">Wikipedia</cite></p>
			
			<p class="post-footer">
				<span class="date">April 26, 2007</span> | 
				<span class="cats"><a href="#">Amadeus</a>, <a href="#">Royalty</a></span> | 
				<a href="#" class="permalink">Permalink</a>
			</p>
		
		</div>
		
		<div class="post">
		
			<h2><a href="#">Lorem Ipsum Dolor Sit Amet</a></h2>
			
			<p>Amadeus William Grabau was an German-American paleontologist and geologist who was born on January 9, 
			1870 in Cedarburgh, Wisconsin in the United States and died on March 20, 1946 in Peking, China. He was 
			employed as faculty at MIT and Rensselaer Polytechnic Institute. In 1901 he became a professor at Columbia 
			University in New York and he later become professor at Peking National University in 1919. As part of his 
			life's work, he conducted a geologic survey of China, and is now known as the father of Chinese geology.</p>
			
			<p>He was also a prolific author, publishing at least 10 books in the first half of the 20th century. Grabau 
			developed various theories during his lifetime, among them the theory of rhythms concerning the growth of the 
			earth's crust and a theory concerning mountain building and creation. The Dorsum Grabau, a wrinkle-ridge found 
			on the moon is named after him.</p>
			
			<p>According to <cite title="Wikipedia">Wikipedia</cite></p>
			
			<p class="post-footer">
				<span class="date">April 26, 2007</span> | 
				<span class="cats"><a href="#">Amadeus</a>, <a href="#">Royalty</a></span> | 
				<a href="#" class="permalink">Permalink</a>
			</p>
		
		</div>
		
		<div class="post">
		
			<h2><a href="#">Lorem Ipsum Dolor Sit Amet</a></h2>
			
			<p>Amadeus William Grabau was an German-American paleontologist and geologist who was born on January 9, 
			1870 in Cedarburgh, Wisconsin in the United States and died on March 20, 1946 in Peking, China. He was 
			employed as faculty at MIT and Rensselaer Polytechnic Institute. In 1901 he became a professor at Columbia 
			University in New York and he later become professor at Peking National University in 1919. As part of his 
			life's work, he conducted a geologic survey of China, and is now known as the father of Chinese geology.</p>
			
			<p>He was also a prolific author, publishing at least 10 books in the first half of the 20th century. Grabau 
			developed various theories during his lifetime, among them the theory of rhythms concerning the growth of the 
			earth's crust and a theory concerning mountain building and creation. The Dorsum Grabau, a wrinkle-ridge found 
			on the moon is named after him.</p>
			
			<p>According to <cite title="Wikipedia">Wikipedia</cite></p>
			
			<p class="post-footer">
				<span class="date">April 26, 2007</span> | 
				<span class="cats"><a href="#">Amadeus</a>, <a href="#">Royalty</a></span> | 
				<a href="#" class="permalink">Permalink</a>
			</p>
		
		</div>
		
		<div class="post">
		
			<h2><a href="#">Lorem Ipsum Dolor Sit Amet</a></h2>
			
			<p>Amadeus William Grabau was an German-American paleontologist and geologist who was born on January 9, 
			1870 in Cedarburgh, Wisconsin in the United States and died on March 20, 1946 in Peking, China. He was 
			employed as faculty at MIT and Rensselaer Polytechnic Institute. In 1901 he became a professor at Columbia 
			University in New York and he later become professor at Peking National University in 1919. As part of his 
			life's work, he conducted a geologic survey of China, and is now known as the father of Chinese geology.</p>
			
			<p>He was also a prolific author, publishing at least 10 books in the first half of the 20th century. Grabau 
			developed various theories during his lifetime, among them the theory of rhythms concerning the growth of the 
			earth's crust and a theory concerning mountain building and creation. The Dorsum Grabau, a wrinkle-ridge found 
			on the moon is named after him.</p>
			
			<p>According to <cite title="Wikipedia">Wikipedia</cite></p>
			
			<p class="post-footer">
				<span class="date">April 26, 2007</span> | 
				<span class="cats"><a href="#">Amadeus</a>, <a href="#">Royalty</a></span> | 
				<a href="#" class="permalink">Permalink</a>
			</p>
		
		</div>
		
		<div class="post last">
		
			<h2><a href="#">Lorem Ipsum Dolor Sit Amet</a></h2>
			
			<p>Amadeus William Grabau was an German-American paleontologist and geologist who was born on January 9, 
			1870 in Cedarburgh, Wisconsin in the United States and died on March 20, 1946 in Peking, China. He was 
			employed as faculty at MIT and Rensselaer Polytechnic Institute. In 1901 he became a professor at Columbia 
			University in New York and he later become professor at Peking National University in 1919. As part of his 
			life's work, he conducted a geologic survey of China, and is now known as the father of Chinese geology.</p>
			
			<p>He was also a prolific author, publishing at least 10 books in the first half of the 20th century. Grabau 
			developed various theories during his lifetime, among them the theory of rhythms concerning the growth of the 
			earth's crust and a theory concerning mountain building and creation. The Dorsum Grabau, a wrinkle-ridge found 
			on the moon is named after him.</p>
			
			<p>According to <cite title="Wikipedia">Wikipedia</cite></p>
			
			<p class="post-footer">
				<span class="date">April 26, 2007</span> | 
				<span class="cats"><a href="#">Amadeus</a>, <a href="#">Royalty</a></span> | 
				<a href="#" class="permalink">Permalink</a>
			</p>
		
		</div>
	
	</div>
